version: "3.7"
services:
  jupyterlab:
    image: jupyterlab:latest
    command: 
      - "jupyter"
      - "lab"
      - "--allow-root"
      - "--ip=0.0.0.0"
      - "--port=${JUPYTERLAB_PORT}"
      - "--no-browser"
      - "--LabApp.token=''"
    # 'init: true' indicates Docker will handle child process reaping
    # This is critical for Jupyter to run correctly.
    init: true
    ports:
      - "${JUPYTERLAB_PORT}:${JUPYTERLAB_PORT}"
    volumes:
      - ${HOME}/${REPOS}/arc_study/arc/:${PYTHON_SITE_PACKAGES}/arc/
      - ${HOME}/${REPOS}/arc_study/data/:/jupyter/data/
      - ${HOME}/${VOLUMES}/notebooks/:/jupyter/notebooks/
      - ${HOME}/${VOLUMES}/configuration/.jupyter/:/root/.jupyter/
